# GENERATED BY intent
# DO NOT EDIT

default:
    @just --list

test:
    pytest -q

eval_clean:
    python3 -m atlas.evaluate --dataset data/gold/v0_slice.jsonl --write-report --report-label clean

eval_noisy:
    python3 -m atlas.evaluate --dataset data/gold/v0_noisy_slice.jsonl --write-report --report-label noisy

eval_readback:
    python3 -m atlas.evaluate --readback-dataset data/gold/readback_pairs.v0.jsonl --write-report --report-label readback

intent_check:
    intent check
